### ISSUE TITLE
MalformedJsonException

### ISSUE THREAD

**Issue by hiyama283** [terminalsin/skidfuscator-java-obfuscator#33]
When I tried to obfuscate an application I created, this error occurred and obfuscator froze.
I can't upload the jar file itself because of the risk of it being lost, but I can tell you that it is a jar file containing a very large txt file for information.

`
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 52221 column 52 path $.contents.classes..flds[0].val
        at com.google.gson.Gson.fromJson(Gson.java:942)
        at com.google.gson.Gson.fromJson(Gson.java:865)
        at dev.skidfuscator.jghost.GhostHelper.readFromLibraryFile(GhostHelper.java:83)
        at dev.skidfuscator.jghost.GhostHelper.getLibrary(GhostHelper.java:56)
        at dev.skidfuscator.jghost.GhostHelper.getJvm(GhostHelper.java:32)
        at dev.skidfuscator.obfuscator.Skidfuscator.run(Skidfuscator.java:381)
        at dev.skidfuscator.obfuscator.command.ObfuscateCommand.call(ObfuscateCommand.java:170)
        at dev.skidfuscator.obfuscator.command.ObfuscateCommand.call(ObfuscateCommand.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.skidfuscator.obfuscator.SkidfuscatorMain.main(SkidfuscatorMain.java:66)
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 52221 column 52 path $.contents.classes..flds[0].val
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
        at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1559)
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1014)
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
        at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:76)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        ... 16 more
`

**Comment by hiyama283** [comment]
Resolved.
Probably an error due to different drives.
